from typing import Literal

class Response:
    @property
    def completed(self) -> bool: ...
    @property
    def status_code(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def reason(self) -> str: ...

    def json(self) -> dict: ...

    def __iter__(self) -> Response: ...
    def __next__(self) -> None: ...

def request(
        method: Literal["GET", "POST", "PUT", "DELETE", "PATCH"],
        url: str,
        headers=None,
        body: str | bytes = None,
        timeout=None) -> Response:
    """Send an HTTP request via non-blocking I/O."""
